### ISSUE TITLE
Updating AppImage via GitHub doesn't work

### ISSUE THREAD

**Issue by fiftydinar** [mijorus/gearlever#105]
I try to put r2modman AppImage link into GitHub URL, but it doesn't work.

1. I choose GitHub as the updating link method
2. I insert this link: `https://github.com/ebkr/r2modmanPlus/releases/download/v*/r2modman-*.AppImage`
Link of latest version as of now: https://github.com/ebkr/r2modmanPlus/releases/download/v3.1.49/r2modman-3.1.49.AppImage
3. I save the update info
4. I refresh the AppImage metadata
5. I notice that the link is changed to https://github.com/ebkr/r2modmanPlus/releases/download/latest/r2modman-3.1.49.AppImage
which doesn't work.

Notice how `v3.1.49` changed to `latest` automatically for some reason.

**Comment by mijorus** [comment]
The URL should change to latest, that's to be expected.

The globe * symbol should remain though

**Comment by mijorus** [comment]
I get it now, the updated URL should be

https://github.com/ebkr/r2modmanPlus/releases/latest/download/r2modman-3.1.49.AppImage

(Download and releases are swapped

**Comment by mijorus** [comment]
Hi @fiftydinar,
I tested this app with the url you pasted here.

The format you specified should be correct, it is working just fine for me.

The `v3.1.49` should change to latest (or <latest>, as it should show up the latest release). This is because that part of the url is a variable, Gear Lever will always get the latest release, no matter what.

**Comment by mijorus** [comment]
Hi, the latest version should include a bunch of bug fix that should fix this issue, please let me know if the issue was fixed for you

**Comment by fiftydinar** [comment]
I confirm it works now, thanks
