### ISSUE TITLE
[Feature Request] Add an option to customize appimage icon

### ISSUE THREAD

**Issue by ghost** [mijorus/gearlever#11]
Hi, on first place, what an amazing and well integrated into gnome-ecosystem app, is just wonderful the fact that is functional and it also uses libadwaita!

Now, about the feature request, could we have a way to change the icon of our appimages? These decide the icon that is going to be use, and sadly never match the proper icon theme, this applies even for gnome default adwaita icons (example: Discord) i would love to see a way to change the icons for each app image on gear level if it is possible!

Again, thanks for all your work because I really like the app so much when I test it today, good luck with the project too!

**Comment by ShortMomo** [comment]
I'm actually going to chime in here and suggest that the feature be something that can edit the general .desktop file. I encountered an issue earlier where the .desktop file for DuckStation was malformed (It added a line like TryExec=duckstation-qt which was causing the icon not to show up in Gnome's app drawer for some reason) which I fixed by manually editing the file. I think it would be handy if we had a way to not only change the icon for the AppImage, but also have a shortcut to open the .desktop file that Gear lever generates in your default text editor in case you need to repair or adjust something about it (like passing launch arguments).
