### ISSUE TITLE
AppImage Update

### ISSUE THREAD

**Issue by Fail-gh** [mijorus/gearlever#29]
Add the option to update AppImages

**Comment by mijorus** [comment]
Hi @Fail-gh ,
currently there isn't a way to automatically update AppImages: while a standard [has been developed](https://github.com/AppImageCommunity/AppImageUpdate), basically nobody is using it.

I tested many apps, but none of them was using this solution.

So, in order to update an app, you can save a custom URL and use that to check manually if there are any updates.

Most importantly, when updating an app, the new version **can automatically replace** the old one,  which makes updating an appimage really easy

**Comment by catbabylon** [comment]
I've noticed that Wezterm and firefox-beta appimages make use of  appimageupdate and it seems to work fine. appimagelauncher adds the option to update the appimage as a right-click menu item in the .desktop file which is very convenient. Is this something you could review as a possible feature for gearlever? gearlever seems to work better at finding the icons and adding the apps to the destop environment than appimagelauncher so it would be great to have update as well...

Thanks for making this app!
