### ISSUE TITLE
Predictable AppImage path

### ISSUE THREAD

**Issue by ticky** [mijorus/gearlever#52]
Hi there, first of all thanks so much for Gear Lever, it's a super handy tool!

I would love to see the option of AppImages having a file name which will be static between updates. I have a few AppImages which I launch via external applications, the references to which I have to update each time I update the application, as the hash-based filename changes with each version. My current workaround is to either launch via a glob path (which isn't necessarily possible all the time) or using a wrapper shell script to do much the same.

This could also help with support for portable configurations as requested in #50, where each update you'd currently need to rename your existing AppImage home or config directories to match the new file name.

**Comment by mijorus** [comment]
Hi @ticky,
First of all, I would like to point out that there is an option called "Use executable name for terminal apps", which does more or less what you say.

This, however, only works if the app you are integrating registers as a command line utility.

Also, since https://github.com/mijorus/gearlever/commit/781a6e11513f299c68acb6fc834b0cddcba956ac app names should be preserved on "update" (where, with update, I mean choosing the REPLACE option when opening a new version of the same app)

Let me know if this helps you, otherwise I might need to add logics to replace the hash with something else, or remove it entirely.

**Comment by ticky** [comment]
Oh! Sounds like you're way ahead of me, then. I think I must've been testing on an older version. I'll keep an eye on it next time I update an app.

I knew of the "executable name for terminal apps" thing but it doesn't have any effect on the apps I was using.

**Comment by dCo3lh0** [comment]
yeah, i do agree with ticky, having a static name or customized static name would be good for the appimage file, the symbolic link for any of these paths "/usr/bin" or "/usr/local/bin" "~/.local/bin", to be customized as well as on the desktop file. For example, i do use an application called Streamlink-Twitch-GUI, which is an appimage, it invokes streamlink official cli application as an appimage as well on terminal by the alias streamlink on /usr/bin/streamlink, it invokes as well the player by the alias in the terminal not by the desktop file "/usr/bin/implay" or "/usr/bin/moonplayer", this is a good example of the need for a custom alias for the terminal.

**Comment by mijorus** [comment]
Since version 2, Gear Lever is not using the weird prefix anymore.
