### ISSUE TITLE
add an option to disable the "gearlever_" prefix

### ISSUE THREAD

**Issue by Kyr4l** [mijorus/gearlever#67]
this sounds like a good feature but from my perspective it clutters the autocompletion and it feels very unecessary & redundant. having each appimage name begin with "gearlever_" doesn't provide anything useful to the end user. being able to disable this feature would be great

**Comment by mijorus** [comment]
Hi, 
version 1.5.0 will include an option to disable the prefix and the hash, basically apps will be save as `<appname>.appimage`, where `<appname> is the name of the app from the desktop file.

This would be an opt-in option, you can enable it in the settings an will work from now on.
Make it so that GearLever would rename all the existing files on the fly would have been quite complicated to do and it could have introduced new bugs

**Comment by mijorus** [comment]
Thanks for contributing with this bug report.

If you want to support my work, please consider a small donation.

https://ko-fi.com/mijorus
